CREATE TABLE USERS (
USERNAME VARCHAR(50) PRIMARY KEY,
PASSWORD VARCHAR(256) NOT NULL,
ENABLED TINYINT(1) NOT NULL
);
CREATE TABLE AUTHORITIES(
USERNAME VARCHAR(50) NOT NULL,
AUTHORITY VARCHAR(50) NOT NULL,
FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);